const Menu = [
    {
        id: 1,
        image: "images/Buttermilk-Pancake.jpg",
        name: "Buttermilk-Pancake",
        category: "Breakfast",
        price: 95,
        description: "Lorem Ipsum sit domet consecutor  iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis",
    },
    {
        id: 2,
        image: "images/egg-mayo-sandwich.jpg",
        name: "Egg Mayo Sandwich",
        category: "Breakfast",
        price: 115,
        description: "Quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatu",
    },
    {
        id: 3,
        image: "images/paratha-roll.jpg",
        name: "Paratha Roll - Our special Lunch",
        category: "Lunch",
        price: 75,
        description: "Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur",
    },
    {
        id: 4,
        image: "images/Potato-lollipop.jpg",
        name: "Potato lollipop",
        category: "Lunch",
        price: 140,
        description: "Lorem Ipsum sit domet consecutor",
    },
    {
        id: 5,
        image: "images/momo.jpg",
        name: "Momo",
        category: "Evening",
        price: 185,
        description: "Lorem Ipsum sit domet consecutor ",
    },
    {
        id: 6,
        image: "images/Chinese-scallion-noodles.jpg",
        name: "Chinese Scallion Noodles",
        category: "Evening",
        price: 225,
        description: "Lorem Ipsum sit domet consecutor",
    },
    {
        id: 7,
        image: "images/roti-tarkari.jpeg",
        name: "Roti Tarkari",
        category: "Dinner",
        price: 195,
        description: "Lorem Ipsum sit domet consecutor",
    },
    {
        id: 8,
        image: "images/Nepali-Khana.jpg",
        name: "Nepali Khana",
        category: "Dinner",
        price: 220,
        description: "Lorem Ipsum sit domet consecutor",
    },
    {
        id: 9,
        image: "images/potato-nuggets.jpg",
        name: "Potato Nuggets",
        category: "Snacks",
        price: 180,
        description: "Lorem Ipsum sit domet consecutor",
    },
    {
        id: 10,
        image: "images/samosa.jpg",
        name: "Samosa",
        category: "Snacks",
        price: 150,
        description: "Lorem Ipsum sit domet consecutor",
    },
];
export default Menu;